apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea-container
          image: gitea/gitea:1.4
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 22
              name: ssh
